name: qiniu_storage_plugin
description: Qiniu sdk flutter plugin.
version: 0.1.1
homepage: https://github.com/atishoo/qiniu_plugin_for_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: plugin.storage.qiniu
    pluginClass: QiniuStoragePlugin

